# Generated by Django 6.0.7 on 2026-07-17 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('clave_curso', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('horas_semanales', models.IntegerField(blank=True, null=True)),
                ('semestre_pertenece', models.IntegerField(blank=True, null=True)),
                ('creditos', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('num_empleado', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=100)),
                ('correo_institucional', models.EmailField(max_length=100, unique=True)),
                ('numero_telefonico', models.CharField(blank=True, max_length=15, null=True)),
                ('especialidad', models.CharField(blank=True, max_length=50, null=True)),
                ('estatus_laboral', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('matricula', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido_paterno', models.CharField(max_length=50)),
                ('apellido_materno', models.CharField(blank=True, max_length=50, null=True)),
                ('correo_electronico', models.EmailField(max_length=100, unique=True)),
                ('numero_telefonico', models.CharField(blank=True, max_length=15, null=True)),
                ('semestre', models.IntegerField(blank=True, null=True)),
                ('estatus_academico', models.CharField(default='activo', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PeriodoEscolar',
            fields=[
                ('clave_periodo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre_periodo', models.CharField(max_length=50)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_termino', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(default='planeado', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('clave_grupo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('dias_clase', models.CharField(blank=True, max_length=50, null=True)),
                ('aula', models.CharField(blank=True, max_length=20, null=True)),
                ('cupo_maximo', models.IntegerField(blank=True, null=True)),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_termino', models.TimeField(blank=True, null=True)),
                ('clave_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.curso')),
                ('num_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.docente')),
                ('clave_periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.periodoescolar')),
            ],
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id_inscripcion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inscripcion', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(default='activa', max_length=20)),
                ('calificacion_final', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('asistencias', models.IntegerField(default=0)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('clave_grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.grupo')),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.estudiante')),
            ],
            options={
                'unique_together': {('matricula', 'clave_grupo')},
            },
        ),
    ]
